# Generated by Django 5.1.5 on 2026-09-15 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("knowledge", "Knowledge Base guide"),
                            ("legal", "Legal page"),
                        ],
                        db_index=True,
                        default="knowledge",
                        max_length=20,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers are listed first."
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ArticleSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Plain text. Blank lines start a new paragraph.",
                    ),
                ),
                (
                    "code",
                    models.TextField(
                        blank=True,
                        help_text="Optional code sample shown under the text.",
                    ),
                ),
                (
                    "code_language",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "csharp", "xml", "text".',
                        max_length=30,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="knowledge.article",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
