# Generated by Django 5.1.5 on 2026-07-15 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_user_role'),
        ('catalog', '0009_product_rejection_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Forces a password change on next login (set when an admin issues a password).'),
        ),
        migrations.AddField(
            model_name='user',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Set for partner self-service logins — grants access to the partner portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='catalog.partner'),
        ),
    ]
