# Generated by Django 5.1.5 on 2026-07-16 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_must_change_password_user_partner'),
        ('catalog', '0010_partner_rejection_note_partner_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='must_change_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Set when this account submits a seller application — see catalog.Partner.status for whether they actually have partner-portal access yet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='catalog.partner'),
        ),
    ]
