# Generated by Django 5.1.5 on 2026-08-05 14:34

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_must_change_password_alter_user_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, choices=[('architect', 'Architect'), ('structural_engineer', 'Structural Engineer'), ('mep_engineer', 'MEP Engineer'), ('civil_engineer', 'Civil Engineer'), ('bim_manager', 'BIM Manager'), ('bim_coordinator', 'BIM Coordinator'), ('bim_modeler', 'BIM Modeler / Technician'), ('contractor', 'Contractor'), ('project_manager', 'Project Manager'), ('interior_designer', 'Interior Designer'), ('construction_manager', 'Construction Manager'), ('estimator', 'Estimator'), ('educator', 'Educator / Trainer'), ('student', 'Student'), ('other', 'Other')], max_length=30),
        ),
    ]
