# Generated by Django 5.1.5 on 2026-09-06 10:24

from django.db import migrations, models


def promote_existing_staff_to_admin(apps, schema_editor):
    """Deploy-safety: before this migration, every is_staff=True account had full,
    unrestricted admin access via plain IsAdminUser (see accounts/admin_api.py
    history). This migration's sibling code change replaces that with granular,
    role-scoped checks (accounts.permissions.HasAdminPermission) — without this
    step, every current staff member would silently lose all admin-portal access
    the moment this ships. Promote them all to Admin (is_superuser=True) so nobody
    is locked out; the owner can deliberately demote specific accounts to
    Staff-with-limited-permissions afterward, on their own schedule. Reverse is a
    deliberate no-op — there's no safe way to know which accounts were superuser
    before this ran vs. promoted by it (see catalog/migrations/0011 for the same
    reasoning on the staff/partner cleanup migration)."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_staff=True, is_superuser=False).update(is_superuser=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_country_profile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(promote_existing_staff_to_admin, migrations.RunPython.noop),
    ]
