# Generated by Django 5.1.5 on 2026-08-05 09:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('rank', models.PositiveSmallIntegerField(default=1, help_text='Higher tiers include everything the lower ones do. Standard=1, Pro=2, ...')),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('seats_per_product', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlighted as the recommended plan on the pricing page.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('license_key', models.CharField(blank=True, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('card_brand', models.CharField(blank=True, max_length=40)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('note', models.TextField(blank=True, help_text='Staff-only note.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='membership.membershipplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
