# Generated by Django 5.1.5 on 2026-09-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='enrollment',
            field=models.CharField(choices=[('self_serve', 'Join online'), ('request', 'By request (Contact us)'), ('included', 'Included for everyone (no sign-up)')], default='self_serve', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='features',
            field=models.TextField(blank=True, help_text="What the plan includes, one item per line. Shown as the card's checklist."),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='original_monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='original_yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1, help_text='Higher tiers include everything the lower ones do. Free=0, Pro=1, Teams=2, ...'),
        ),
    ]
