# Generated by Django 5.1.5 on 2026-07-19 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0011_strip_staff_partner_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginBuild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revit_year', models.CharField(max_length=16)),
                ('plugin_version', models.CharField(default='1.0.0', max_length=30)),
                ('dll_storage_key', models.CharField(blank=True, max_length=400)),
                ('dll_filename', models.CharField(blank=True, max_length=255)),
                ('addin_storage_key', models.CharField(blank=True, max_length=400)),
                ('addin_filename', models.CharField(blank=True, max_length=255)),
                ('upgrade_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('scope', models.CharField(default='peruser', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('building', 'Building'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('built_msi_storage_key', models.CharField(blank=True, max_length=400)),
                ('build_log', models.TextField(blank=True)),
                ('built_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_builds', to='catalog.product')),
            ],
            options={
                'ordering': ['revit_year'],
            },
        ),
        migrations.CreateModel(
            name='PluginResourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('resource', 'Resource'), ('dependency', 'Dependency')], default='resource', max_length=20)),
                ('storage_key', models.CharField(max_length=400)),
                ('original_filename', models.CharField(max_length=255)),
                ('destination_path', models.CharField(help_text='e.g. {ADDIN_DIR}\\MyPlugin\\config.json or {INSTALL_DIR}\\lib\\dependency.dll', max_length=400)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_files', to='installer.pluginbuild')),
            ],
            options={
                'ordering': ['sort_order', 'original_filename'],
            },
        ),
        migrations.AddConstraint(
            model_name='pluginbuild',
            constraint=models.UniqueConstraint(fields=('product', 'revit_year'), name='unique_plugin_build_per_product_year'),
        ),
    ]
