# Generated by Django 5.1.5 on 2026-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pluginbuild',
            name='build_log',
        ),
        migrations.RemoveField(
            model_name='pluginbuild',
            name='built_at',
        ),
        migrations.RemoveField(
            model_name='pluginbuild',
            name='built_msi_storage_key',
        ),
        migrations.RemoveField(
            model_name='pluginbuild',
            name='status',
        ),
        migrations.AlterField(
            model_name='pluginbuild',
            name='scope',
            field=models.CharField(default='perUser', max_length=16),
        ),
    ]
