# Generated by Django 5.1.5 on 2026-07-14 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, help_text="Snapshot of the actor's email/name.", max_length=180)),
                ('verb', models.CharField(choices=[('signed_in', 'Signed in'), ('signed_up', 'Signed up'), ('claimed_free_product', 'Claimed a free product'), ('downloaded_file', 'Downloaded a file'), ('posted_review', 'Posted a review'), ('product_created', 'Created a product'), ('product_updated', 'Updated a product'), ('product_deleted', 'Deleted a product'), ('license_revoked', 'Revoked a license'), ('license_restored', 'Restored a license'), ('license_extended', 'Extended a license'), ('order_status_changed', "Changed an order's status")], max_length=40)),
                ('target_label', models.CharField(blank=True, help_text='What the action was performed on.', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_ac_created_d34040_idx'), models.Index(fields=['verb'], name='activity_ac_verb_6b9f4c_idx')],
            },
        ),
    ]
