# Generated by Django 5.1.5 on 2026-07-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='verb',
            field=models.CharField(choices=[('signed_in', 'Signed in'), ('signed_up', 'Signed up'), ('claimed_free_product', 'Claimed a free product'), ('downloaded_file', 'Downloaded a file'), ('posted_review', 'Posted a review'), ('product_created', 'Created a product'), ('product_updated', 'Updated a product'), ('product_deleted', 'Deleted a product'), ('product_submitted_for_review', 'Submitted a product for review'), ('product_approved', 'Approved a product'), ('product_rejected', 'Rejected a product'), ('license_revoked', 'Revoked a license'), ('license_restored', 'Restored a license'), ('license_extended', 'Extended a license'), ('order_status_changed', "Changed an order's status")], max_length=40),
        ),
    ]
