# Generated by Django 5.1.5 on 2026-07-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activitylog_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='verb',
            field=models.CharField(choices=[('signed_in', 'Signed in'), ('signed_up', 'Signed up'), ('claimed_free_product', 'Claimed a free product'), ('order_placed', 'Placed an order'), ('downloaded_file', 'Downloaded a file'), ('posted_review', 'Posted a review'), ('product_created', 'Created a product'), ('product_updated', 'Updated a product'), ('product_deleted', 'Deleted a product'), ('product_submitted_for_review', 'Submitted a product for review'), ('product_approved', 'Approved a product'), ('product_rejected', 'Rejected a product'), ('license_revoked', 'Revoked a license'), ('license_restored', 'Restored a license'), ('license_extended', 'Extended a license'), ('license_released', 'Released a machine binding'), ('order_status_changed', "Changed an order's status"), ('order_seats_changed', "Changed an order's seat count"), ('license_code_created', 'Generated a license code'), ('license_code_revoked', 'Revoked a license code'), ('redeemed_license_code', 'Redeemed a license code')], max_length=40),
        ),
    ]
