# Generated by Django 5.1.5 on 2026-07-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
