# Generated by Django 5.1.5 on 2026-07-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_code_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='team_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='team_seats',
        ),
    ]
