# Generated by Django 5.1.5 on 2026-07-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_team_price_remove_product_team_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
