# Generated by Django 5.1.5 on 2026-07-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_productmedia_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
