# Generated by Django 5.1.5 on 2026-07-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rejection_note',
            field=models.TextField(blank=True, help_text='Shown to the submitting partner when status is set to Rejected.'),
        ),
    ]
