# Generated by Django 5.1.5 on 2026-07-16 09:25

from django.db import migrations, models


def approve_existing_partners(apps, schema_editor):
    """New field defaults every row to "pending" — but every Partner that
    already exists was created before seller applications existed at all (via
    admin CRUD or the seed script), so they're already legitimately live, not
    unreviewed applications. Backfill them as approved so they don't vanish
    from the public storefront (PartnerViewSet now filters on this)."""
    Partner = apps.get_model("catalog", "Partner")
    Partner.objects.update(status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_rejection_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.RunPython(approve_existing_partners, migrations.RunPython.noop),
    ]
