# Generated by Django 5.1.5 on 2026-08-05 09:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_collapse_categories_to_revit_plugins'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_release_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Internal name, e.g. 'Back to school 2026'.", max_length=140)),
                ('badge_label', models.CharField(default='SPECIAL OFFER', help_text='Short label on the countdown bar.', max_length=40)),
                ('headline', models.CharField(help_text='The line customers read, e.g. "This price won\'t last long..."', max_length=160)),
                ('cta_label', models.CharField(blank=True, max_length=40)),
                ('cta_url', models.CharField(blank=True, help_text="Where the banner's button goes, e.g. /catalog.", max_length=200)),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('scope', models.CharField(choices=[('all', 'Every product'), ('category', 'One category (and its subcategories)'), ('products', 'Selected products only')], default='all', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, help_text='Switches the promotion off without changing its dates.')),
                ('show_countdown', models.BooleanField(default=True, help_text='Show this promotion in the countdown bar above the nav.')),
                ('priority', models.IntegerField(default=0, help_text='Higher wins when two live promotions cover the same product or want the banner.')),
                ('category', models.ForeignKey(blank=True, help_text="Required when scope is 'category'. Subcategories are included.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalog.category')),
                ('products', models.ManyToManyField(blank=True, help_text="Required when scope is 'products'.", related_name='promotions', to='catalog.product')),
            ],
            options={
                'ordering': ['-priority', 'ends_at'],
                'indexes': [models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='catalog_pro_is_acti_2f438f_idx')],
            },
        ),
    ]
