# Generated by Django 5.1.5 on 2026-08-05 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_last_release_at_promotion'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='membership_plan',
            field=models.ForeignKey(blank=True, help_text='Lowest All-Access tier that includes this product. Blank = not in All-Access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='membership.membershipplan'),
        ),
    ]
