# Generated by Django 5.1.5 on 2026-08-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product_membership_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first in the hero carousel.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hero_featured',
            field=models.BooleanField(default=False, help_text='Show in the homepage hero carousel.'),
        ),
    ]
