# Generated by Django 5.1.5 on 2026-08-05 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_hero_sort_order_product_is_hero_featured'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='plan',
            field=models.ForeignKey(blank=True, help_text="Required when scope is 'plan'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='membership.membershipplan'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='scope',
            field=models.CharField(choices=[('all', 'Every product'), ('category', 'One category (and its subcategories)'), ('products', 'Selected products only'), ('plan', 'One All-Access membership plan')], default='all', max_length=20),
        ),
    ]
