# Generated by Django 5.1.5 on 2026-09-13 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_promotion_plan_alter_promotion_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shown crossed out next to the real price. Leave blank for none.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
