# Generated by Django 5.1.5 on 2026-09-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_original_price_and_full_discounts"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Collection",
        ),
    ]
