# Generated by Django 5.1.5 on 2026-07-12 08:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('revit_year', models.CharField(blank=True, max_length=16)),
                ('default_trial_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_skus', to='catalog.product')),
            ],
            options={
                'db_table': 'license_products',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MachineLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_fingerprint_hash', models.TextField()),
                ('fingerprint_version', models.TextField(default='HWFP-2')),
                ('status', models.TextField(default='active')),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('install_count', models.IntegerField(default=1)),
                ('plugin_version', models.TextField(blank=True)),
                ('machine_data', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_licenses', to='licensing.licensedproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'machine_licenses',
            },
        ),
        migrations.CreateModel(
            name='LicenseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_fingerprint_hash', models.TextField()),
                ('event_type', models.TextField()),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(default=dict)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='licensing.licensedproduct')),
                ('machine_license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='licensing.machinelicense')),
            ],
            options={
                'db_table': 'license_events',
                'ordering': ['-event_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('license_key', models.CharField(blank=True, max_length=64, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='licensing.licensedproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'license_purchases',
                'ordering': ['-requested_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='machinelicense',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_licenses', to='licensing.productpurchase'),
        ),
        migrations.AddConstraint(
            model_name='productpurchase',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_product_purchase_per_user'),
        ),
        migrations.AddConstraint(
            model_name='machinelicense',
            constraint=models.UniqueConstraint(fields=('product', 'machine_fingerprint_hash'), name='unique_machine_license_per_product'),
        ),
    ]
