# Generated by Django 5.1.5 on 2026-07-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelicense',
            name='status',
            field=models.TextField(db_index=True, default='active'),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20),
        ),
    ]
