# Generated by Django 5.1.5 on 2026-07-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_alter_machinelicense_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='seats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
