# Generated by Django 5.1.5 on 2026-07-19 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_productpurchase_seats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LicenseCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=64, unique=True)),
                ('seats', models.PositiveIntegerField(default=1)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unredeemed', 'Unredeemed'), ('redeemed', 'Redeemed'), ('revoked', 'Revoked')], db_index=True, default='unredeemed', max_length=20)),
                ('note', models.CharField(blank=True, help_text='Staff-only note, e.g. who this was issued to and why.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_codes_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_codes', to='licensing.licensedproduct')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_codes_redeemed', to=settings.AUTH_USER_MODEL)),
                ('redeemed_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_license_code', to='licensing.productpurchase')),
            ],
            options={
                'db_table': 'license_codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
