# Generated by Django 5.1.5 on 2026-07-20 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_productpurchase_expires_at_licensecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedproduct',
            name='default_trial_hours',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='licensedproduct',
            name='default_trial_minutes',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='licensedproduct',
            name='default_trial_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
