# Generated by Django 5.1.5 on 2026-07-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_licensedproduct_default_trial_hours_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productpurchase',
            name='unique_product_purchase_per_user',
        ),
    ]
