# Generated by Django 5.1.5 on 2026-07-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0006_remove_productpurchase_unique_product_purchase_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='billing_period',
            field=models.CharField(blank=True, choices=[('', 'One-time'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
