# Generated by Django 5.1.5 on 2026-07-22 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0007_productpurchase_billing_period_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelicense',
            name='used_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='productpurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('is_trial', True)), fields=('user', 'product'), name='one_trial_purchase_per_user_product'),
        ),
    ]
