# Generated by Django 5.1.5 on 2026-07-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0008_machinelicense_used_trial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='card_brand',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
