# Generated by Django 5.1.5 on 2026-08-05 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0009_productpurchase_card_brand_and_more'),
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='source_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granted_purchases', to='membership.membership'),
        ),
        migrations.AddConstraint(
            model_name='productpurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('source_membership__isnull', False)), fields=('user', 'product', 'source_membership'), name='one_membership_purchase_per_user_product'),
        ),
    ]
